name: Hello Comment Bot

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  reply-to-hello:
    if: |
      github.event.comment.body == '@hello' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Reply to PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const username = context.payload.comment.user.login;
            const prNumber = context.payload.issue.number;
            const reply = `hii @${username}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: reply
            });
